### ISSUE TITLE
There is no code in repo

### ISSUE THREAD

**Issue by mammadkoma** [CodeMazeBlog/blazor-series#6]
There is no code in repository.
![image](https://user-images.githubusercontent.com/17564001/149079732-ff5543ef-437a-40d7-b76c-81ae3d7a3443.png)

**Comment by MarinkoSpasojevic** [comment]
Hello there.

Just select a different branch, the main branch is empty.
![image](https://user-images.githubusercontent.com/36244468/149085418-a871aa2d-4a01-4c0d-96ea-a9ab81f87cc3.png)

**Comment by mammadkoma** [comment]
Thank you , I get the first (blazor-series-Branch_blazor-webassembly-partial-classes-renderfragment-lifecycle) but it has only client project without server project.
![image](https://user-images.githubusercontent.com/17564001/149117300-6837ab08-7cd5-4587-8bec-f5cdde6d2478.png)

**Comment by CodeMazeBlog** [comment]
Hey @mammadkoma, there's no need for the server at this point of the series. The server is introduced later on. Check out the article: https://code-maze.com/partial-classes-renderfragment-lifecycle-blazor-wasm/

**Comment by mammadkoma** [comment]
I want to download this article project : https://code-maze.com/blazor-webassembly-series/

**Comment by CodeMazeBlog** [comment]
Each branch has an article link in the readme file. The branch you were talking about is about Partial Classes, RenderFragment, and Lifecycle in Blazor WebAssembly, so that's the link to that particular article.

The link you've shared is the page to the entire Blazor WebAssembly series. 

Hope this helps.

**Comment by mammadkoma** [comment]
Very hard!  
Yes I want the entire Blazor WebAssembly series project.
And there is not any link in readme file:
![image](https://user-images.githubusercontent.com/17564001/149128665-d8a877d9-8204-441b-bc7a-11d8bb427c2f.png)
